'use client'

import { Inter } from "next/font/google";
import "./globals.css";
// import type { Metadata } from "next";
import { Provider } from "react-redux";
import { store } from "./redux/store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider store={store} >
        {children}
        </Provider>
        </body>
    </html>
  );
}
